# Generated by Django 5.1.7 on 2025-03-29 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0004_remove_user_password_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='token',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='storage',
            name='token_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
