# Generated by Django 5.1.7 on 2025-08-09 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0006_alter_storage_last_download_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='token',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
